export const TELEGRAF_MODULE_OPTIONS = 'TELEGRAF_MODULE_OPTIONS';
export const TELEGRAF_PROVIDER = 'TELEGRAF_PROVIDER';

export const DECORATORS_PREFIX = 'TELEGRAF';
export const DECORATORS = {
  USE: `${DECORATORS_PREFIX}/USE`,
  ON: `${DECORATORS_PREFIX}/ON`,
  HEARS: `${DECORATORS_PREFIX}/HEARS`,
  COMMAND: `${DECORATORS_PREFIX}/COMMAND`,
  START: `${DECORATORS_PREFIX}/START`,
  HELP: `${DECORATORS_PREFIX}/HELP`,
  SETTINGS: `${DECORATORS_PREFIX}/SETTINGS`,
  ENTITY: `${DECORATORS_PREFIX}/ENTITY`,
  MENTION: `${DECORATORS_PREFIX}/MENTION`,
};
