export const TELEGRAF_MODULE_OPTIONS = 'TELEGRAF_MODULE_OPTIONS';

export const UPDATE_METADATA = 'UPDATE_METADATA';
export const UPDATE_LISTENER_METADATA = 'UPDATE_LISTENER_METADATA';

export const SCENE_METADATA = 'SCENE_METADATA';
